// src/app/reglementation/page.jsx
import Link from 'next/link';

export default function Reglementation() {
  return (
    <div>
      <h2>Réglementation</h2>

      <p>
        <b>IMPORTANT NOTICE</b>: AE PIMA is an independent initiative and is not an official website of Sorbonne Université. There is no financial, administrative, public, or any other official affiliation with Sorbonne Université. AE PIMA is a collaborative effort by students to share resources and establish a network of alumni from the PIMA program.
      </p>

      <p>
        The inclusion of basic legal agreements below is an attempt to safeguard ourselves from legal repercussions and potential harm through the legal system. It is important to note that these agreements were generated online, and we, as students, do not possess legal expertise.
      </p>

      <p>
        By consenting to the "réglementation," you are acknowledging and agreeing to the following:
      </p>

      <ul>
        <li>
          <Link href="/reglementation/terms_of_use">Terms of Use</Link>
        </li>
        <li>
          <Link href="/reglementation/acceptable_use_policy">Acceptable Use Policy</Link>
        </li>
        <li>
          <Link href="/reglementation/cookie_policy">Cookie Policy</Link>
        </li>
        <li>
          <Link href="/reglementation/privacy_policy">Privacy Policy</Link>
        </li>
        <li>
          <Link href="/reglementation/disclaimer">Disclaimer</Link>
        </li>
        <li>
          <Link href="/reglementation/banana_policy">Banana Policy</Link>
        </li>
      </ul>

      <p>
        Your understanding and compliance with these agreements contribute to a transparent and respectful online environment for all users involved.
      </p>
    </div>
  );
}

// src/routes/reglementation/+page.svelte

<h2>Réglementation</h2>

<p>
    <b>IMPORTANT NOTICE</b>: AE PIMA is an independent initiative and is not an official website of Sorbonne Université. There is no financial, administrative, public, or any other official affiliation with Sorbonne Université. AE PIMA is a collaborative effort by students to share resources and establish a network of alumni from the PIMA program.
</p>

<p>
    The inclusion of basic legal agreements below is an attempt to safeguard ourselves from legal repercussions and potential harm through the legal system. It is important to note that these agreements were generated online, and we, as students, do not possess legal expertise.
</p>

<p>
    By consenting to the "réglementation," you are acknowledging and agreeing to the following:
</p>

<ul>
    <li><a href="/reglementation/terms_of_use">Terms of Use</a></li>
    <li><a href="/reglementation/acceptable_use_policy">Acceptable Use Policy</a></li>
    <li><a href="/reglementation/cookie_policy">Cookie Policy</a></li>
    <li><a href="/reglementation/privacy_policy">Privacy Policy</a></li>
    <li><a href="/reglementation/disclaimer">Disclaimer</a></li>
    <li><a href="/reglementation/banana_policy">Banana Policy</a></li>
</ul>

Your understanding and compliance with these agreements contribute to a transparent and respectful online environment for all users involved.
