// src/routes/reglementation/banana_policy/+page.svelte
<h2>Banana Policy</h2>

<p>
    Monkey go crazy, monkey go <i>B A N A E N A E ~</i>. UUUGGGAAAA BUUUGAAAAA
    UUUUAAA UAUUAAAAA UAAAAAA AAAAAHHH AHHAHAHAHHHHAHHAHHAHHAH AYYAYAYAYYAYAYAY
    UGAGAGAGAGAGAA AAAAA UYUAYUAYAUYAUYAAAA AGHAJAHAJAJJA AGGAGAGAGGAA 
    JAJAJAJAJAJAJAJA AHAHAHAHAH <b>AAAAHH AHAAAUAUUAAUAUAUAU</b>
    <i>BAANNAANAA</i> MONKEY WANT <b>BANANAAANAA!!!</b> 
</p>
<h2>MONEKY NEED BANANA NOWWWW !!!</h2>

<p>
    BANAN 🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌
    🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌
    🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌
</p>
<p>
   𝓞ⓝⓚⓔу 𝐆Ỗ в Δ Ň ａ 𝓔 𝕟 Δ 𝒆 ~. ⓤ𝐔𝓤ⓖ𝓰𝓖Δ𝔞ａÃ в𝓤ย𝔲𝔾Δａᗩ𝔸𝕒    ỮＵ𝓊Ǘ𝕒ａÃ ⓤᗩᑌ𝓤𝔞𝓪𝐚ᗩά 𝐔ᗩαⓐΔα𝒶 𝓐αΔ𝔸คⓗⓗ𝓱 𝐚ħ𝐇𝓐𝒽ᵃ𝔥ᗩн𝐡нĤάℍⒽαⒽ𝕙คℍ𝐇α𝒽 𝐀үуⓐ𝔶𝕒үάʸƳ𝓐𝐲Ａץⓐ𝕐    υg𝔞𝐠ค𝐠α𝕘ᗩＧ𝒶𝔤𝒶𝕒 α卂ᗩΔΔ 𝕌𝓎υａ₳₳₳ ɄɎɄ₳ɎɄ₳Ɏ₳ɄɎ₳ɄɎ₳₳₳₳ ₳₲Ⱨ₳J₳Ⱨ₳J₳JJ₳ ₳₲₲₳₲₳₲₳₲₲₳₳     J₳J₳J₳J₳J₳J₳J₳J₳ ₳Ⱨ₳Ⱨ₳Ⱨ₳Ⱨ₳Ⱨ ₳₳₳₳ⱧⱧ ₳Ⱨ₳₳₳Ʉ₳ɄɄ₳₳Ʉ₳Ʉ₳Ʉ₳Ʉ    ฿₳₳₦₦₳₳₦₳₳ ₥Ø₦₭ɆɎ ₩₳₦₮ ฿₳₦₳₦₳₳₳₦₳₳!!!
    爪ㄖ几Ҝ乇ㄚ Ꮆㄖ 匚尺卂乙ㄚ, 爪ㄖ几Ҝ乇ㄚ Ꮆㄖ 乃 卂 几 卂 乇 几 卂 乇 ~. ㄩㄩㄩᎶᎶᎶ卂卂卂卂 乃ㄩㄩㄩᎶ卂卂卂卂卂    ㄩㄩㄩㄩ卂卂卂 ㄩ ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ卂卄卂ﾌ卂ﾌﾌ卂 卂ᎶᎶ卂Ꮆ卂Ꮆ卂ᎶᎶ卂卂     ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂 卂卄卂卄ǟʝǟʝǟʝǟʝǟ ǟɦǟɦǟɦǟɦǟɦ ǟǟǟǟɦɦ ǟɦǟǟǟʊǟʊʊǟǟʊǟʊǟʊǟʊ    ɮǟǟռռǟǟռǟǟ ʍօռӄɛʏ աǟռȶ ɮǟռǟռǟǟǟռǟǟ!!!
    ₥Ø₦₭ɆɎ ₲Ø ₵Ɽ₳ⱫɎ, ₥Ø₦₭ɆɎ ₲Ø ฿ ₳ ₦ ₳ Ɇ ₦ ₳ Ɇ ~. ɄɄɄ₲₲₲₳₳₳₳ ฿ɄɄɄ₲₳₳₳₳₳    ɄɄɄɄ₳₳₳ Ʉ₳ɄɄ₳₳₳₳₳ Ʉ₳₳₳₳₳₳ ₳₳₳₳₳ⱧⱧⱧ ₳ⱧⱧ₳Ⱨ₳Ⱨ₳ⱧⱧⱧⱧ₳ⱧⱧ₳ⱧⱧ₳ⱧⱧ₳Ⱨ ₳ɎɎ₳Ɏ₳Ɏ₳ɎɎ₳Ɏ₳Ɏ₳Ɏ    Ʉ₲₳₲₳₲₳₲₳₲₳₲₳₳ ₳₳ ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ卂卄卂ﾌ卂ﾌﾌ卂 卂ᎶᎶ卂Ꮆ卂Ꮆ卂ᎶᎶ卂卂     ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂卄卂卄卂卄 卂卂卂卂卄卄 卂卄卂卂卂ㄩ卂ㄩㄩ卂卂ㄩ卂ㄩ卂ㄩ卂ㄩ    乃卂卂几几卂卂₳ⱧⱧⱧⱧ₳ⱧⱧ₳ⱧⱧ₳ⱧⱧ₳Ⱨ ₳ɎɎ₳Ɏ₳Ɏ₳ɎɎ₳Ɏ₳Ɏ₳Ɏ    Ʉ₲₳₲₳₲₳₲₳₲₳₲₳₳ ₳₳ ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ卂卄卂ﾌ卂ﾌﾌ卂 卂ᎶᎶ卂Ꮆ卂Ꮆ卂ᎶᎶ卂卂     ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂卄卂卄卂卄 卂卂卂卂卄卄 卂卄卂卂卂ㄩ卂ㄩㄩ卂卂ㄩ卂ㄩ卂ㄩ卂ㄩ    乃卂卂几几卂卂几卂卂 爪ㄖ几Ҝ乇ㄚ 山卂几ㄒ 乃卂几卂几卂Δ 𝕌𝓎υａʸᵘⒶ𝐘Ⓐ𝕌у𝐚𝓾𝓎ⓐⒶ𝕒ᗩ ａᵍ𝔥Ａ𝐣𝓪卄𝓪נ𝐀јʲα 𝔞ᎶⒼ𝓪𝐠𝐀ᵍ𝓐𝓖𝔤Ã𝔞     ⓙⒶڶⓐ𝕁ค𝕁ⓐјα𝒿ⒶןＡ𝓳𝔞 𝓪ℍ𝒶н𝐀ħ𝔞ђ𝔸ђ Ãάα𝔞Ħⓗ ⓐ𝕙ᵃ𝐚𝓪𝔲ⓐＵỮ𝒶𝕒Ｕᗩᵘค𝓾Δ𝔲    乃ⒶÃＮ𝓃ᗩ𝐚𝐧ά𝓐 𝓶ᵒŇ𝐊ｅ𝓨 山ά几ｔ 𝕓𝓪ｎ卂ηα𝒶άᑎＡΔ!!! ~舞*'¨¯¨'*·~漫-ǟɦɦ ǟɦǟǟǟʊǟʊʊǟǟʊǟʊǟʊǟʊ    ɮǟǟռռǟǟռǟǟ ʍօռӄɛʏ աǟռȶ ɮǟռǟռǟǟǟռǟǟ!!!
    ₥Ø₦₭ɆɎ ₲Ø ₵Ɽ₳ⱫɎ, ₥Ø₦₭ɆɎ ₲Ø ฿ ₳ ₦ ₳ Ɇ ₦ ₳ Ɇ ~. ɄɄɄ₲₲₲₳₳₳₳ ฿ɄɄɄ₲₳₳₳₳₳    ɄɄɄɄ₳₳₳ Ʉ₳ɄɄ₳₳₳₳₳ Ʉ₳₳₳₳₳₳ ₳₳₳₳₳ⱧⱧⱧ ₳ⱧⱧ₳Ⱨ₳Ⱨ₳ⱧⱧⱧⱧ₳ⱧⱧ₳ⱧⱧ₳ⱧⱧ₳Ⱨ ₳ɎɎ₳Ɏ₳Ɏ₳ɎɎ₳Ɏ₳Ɏ₳Ɏ    Ʉ₲₳₲₳₲₳₲₳₲₳₲₳₳ ₳₳ ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ卂卄卂ﾌ卂ﾌﾌ卂 卂ᎶᎶ卂Ꮆ卂Ꮆ卂ᎶᎶ卂卂     ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂卄卂卄卂卄 卂卂卂卂卄卄 卂卄卂卂卂ㄩ卂ㄩㄩ卂卂ㄩ卂ㄩ卂ㄩ卂ㄩ    乃卂卂几几卂卂₳ⱧⱧⱧⱧ₳ⱧⱧ₳ⱧⱧ₳ⱧⱧ₳Ⱨ ₳ɎɎ₳Ɏ₳Ɏ₳ɎɎ₳Ɏ₳Ɏ₳Ɏ    Ʉ₲₳₲₳₲₳₲₳₲₳₲₳₳ ₳₳ ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ𝓪𝐚ᗩά 𝐔ᗩαⓐΔα𝒶 𝓐αΔ𝔸คⓗⓗ𝓱 𝐚ħ𝐇𝓐𝒽ᵃ𝔥ᗩн𝐡нĤάℍⒽαⒽ𝕙คℍ𝐇α𝒽 𝐀үуⓐ𝔶𝕒үάʸƳ𝓐𝐲Ａץⓐ𝕐    υg𝔞𝐠ค𝐠α𝕘ᗩＧ𝒶𝔤𝒶𝕒 α卂ᗩΔΔ 𝕌
</p>
<h1>B A N A N</h1>
<p>
    ✧✴  🎀  𝐵𝒜𝒩𝒜𝒩𝒜  🎀  ✴✧
    <br/>
    <br/>
    <br/>
    ʍօռӄɛʏ ɢօ ƈʀǟʐʏ, ʍօռӄɛʏ ɢօ ɮ ǟ ռ ǟ ɛ ռ ǟ ɛ ~. ʊʊʊɢɢɢǟǟǟǟ ɮʊʊʊɢǟǟǟǟǟ    ʊʊʊʊǟǟǟ ʊǟʊʊǟǟǟǟǟ ʊǟǟǟǟǟǟ ǟǟǟǟǟɦɦɦ ǟɦɦǟɦǟɦǟɦɦɦɦǟɦɦǟɦɦǟɦɦǟɦ ǟʏʏǟʏǟʏǟʏʏǟʏǟʏǟʏ    ʊɢǟɢǟɢǟɢǟɢǟɢǟǟ ǟǟǟǟǟ ʊʏʊǟʏʊǟʏǟʊʏǟʊʏǟǟǟǟ ǟɢɦǟʝǟɦǟʝǟʝʝǟ ǟɢɢǟɢǟɢǟɢɢǟǟ     ʝǟʝǟʝǟʝǟʝǟʝǟʝǟʝǟ ǟɦǟɦǟɦǟɦǟɦ ǟǟǟǟɦɦ ǟɦǟǟǟʊǟʊʊǟǟʊǟʊǟʊǟʊ    ɮǟǟռռǟǟռǟǟ ʍօռӄɛʏ աǟռȶ ɮǟռǟռǟǟǟռǟǟ!!!
    ₥Ø₦₭ɆɎ ₲Ø ₵Ɽ₳ⱫɎ, ₥Ø₦₭ɆɎ ₲Ø ฿ ₳ ₦ ₳ Ɇ ₦ ₳ Ɇ ~. ɄɄɄ₲₲₲₳₳₳₳ ฿ɄɄɄ₲₳₳₳₳₳    ɄɄɄɄ₳₳₳ Ʉ₳ɄɄ₳₳₳₳₳ Ʉ₳₳₳₳₳₳ ₳₳₳₳₳ⱧⱧⱧ ₳ⱧⱧ₳Ⱨ₳Ⱨ₳ⱧⱧⱧⱧ₳ⱧⱧ₳ⱧⱧ₳ⱧⱧ₳Ⱨ ₳ɎɎ₳Ɏ₳Ɏ₳ɎɎ₳Ɏ₳Ɏ₳Ɏ    Ʉ₲₳₲₳₲₳₲₳₲₳₲₳₳ ₳₳ ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ卂卄卂ﾌ卂ﾌﾌ卂 卂ᎶᎶ卂Ꮆ卂Ꮆ卂ᎶᎶ卂卂     ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂 卂卄卂卄卂卄卂卄卂卄 卂卂卂卂卄卄 卂卄卂卂卂ㄩ卂ㄩㄩ卂卂ㄩ卂ㄩ卂ㄩ卂ㄩ    乃卂卂几几卂卂几卂卂 爪ㄖ几Ҝ乇ㄚ 山卂几ㄒ 乃卂几卂几卂卂卂几卂卂!!!
    -漫~*'¨¯¨'*·舞~ ᵐ𝔬Ň𝕂𝓔у 𝐠Ỗ 𝓒ℝÃ𝐳¥, 𝓂𝓞ⓝⓚⓔу 𝐆Ỗ в Δ Ň ａ 𝓔 𝕟 Δ 𝒆 ~. ⓤ𝐔𝓤ⓖ𝓰𝓖Δ𝔞ａÃ в𝓤ย𝔲𝔾Δａᗩ𝔸𝕒    ỮＵ𝓊Ǘ𝕒ａÃ ⓤᗩᑌ𝓤𝔞𝓪𝐚ᗩά 𝐔ᗩαⓐΔα𝒶 𝓐αΔ𝔸คⓗⓗ𝓱 𝐚ħ𝐇𝓐𝒽ᵃ𝔥ᗩн𝐡нĤάℍⒽαⒽ𝕙คℍ𝐇α𝒽 𝐀үуⓐ𝔶𝕒үάʸƳ𝓐𝐲Ａץⓐ𝕐    υg𝔞𝐠ค𝐠α𝕘ᗩＧ𝒶𝔤𝒶𝕒 α卂ᗩΔΔ 𝕌𝓎υａ₳₳₳ ɄɎɄ₳ɎɄ₳Ɏ₳ɄɎ₳ɄɎ₳₳₳₳ ₳₲Ⱨ₳J₳Ⱨ₳J₳JJ₳ ₳₲₲₳₲₳₲₳₲₲₳₳     J₳J₳J₳J₳J₳J₳J₳J₳ ₳Ⱨ₳Ⱨ₳Ⱨ₳Ⱨ₳Ⱨ ₳₳₳₳ⱧⱧ ₳Ⱨ₳₳₳Ʉ₳ɄɄ₳₳Ʉ₳Ʉ₳Ʉ₳Ʉ    ฿₳₳₦₦₳₳₦₳₳ ₥Ø₦₭ɆɎ ₩₳₦₮ ฿₳₦₳₦₳₳₳₦₳₳!!!
    爪ㄖ几Ҝ乇ㄚ Ꮆㄖ 匚尺卂乙ㄚ, 爪ㄖ几Ҝ乇ㄚ Ꮆㄖ 乃 卂 几 卂 乇 几 卂 乇 ~. ㄩㄩㄩᎶᎶᎶ卂卂卂卂 乃ㄩㄩㄩᎶ卂卂卂卂卂    ㄩㄩㄩㄩ卂卂卂 ㄩ ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ卂卄卂ﾌ卂ﾌﾌ卂 卂ᎶᎶ卂Ꮆ卂Ꮆ卂ᎶᎶ卂卂     ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂 卂卄卂卄ǟʝǟʝǟʝǟʝǟ ǟɦǟɦǟɦǟɦǟɦ ǟǟǟǟɦɦ ǟɦǟǟǟʊǟʊʊǟǟʊǟʊǟʊǟʊ    ɮǟǟռռǟǟռǟǟ ʍօռӄɛʏ աǟռȶ ɮǟռǟռǟǟǟռǟǟ!!!
    ₥Ø₦₭ɆɎ ₲Ø ₵Ɽ₳ⱫɎ, ₥Ø₦₭ɆɎ ₲Ø ฿ ₳ ₦ ₳ Ɇ ₦ ₳ Ɇ ~. ɄɄɄ₲₲₲₳₳₳₳ ฿ɄɄɄ₲₳₳₳₳₳    ɄɄɄɄ₳₳₳ Ʉ₳ɄɄ₳₳₳₳₳ Ʉ₳₳₳₳₳₳ ₳₳₳₳₳ⱧⱧⱧ ₳ⱧⱧ₳Ⱨ₳Ⱨ₳ⱧⱧⱧⱧ₳ⱧⱧ₳ⱧⱧ₳ⱧⱧ₳Ⱨ ₳ɎɎ₳Ɏ₳Ɏ₳ɎɎ₳Ɏ₳Ɏ₳Ɏ    Ʉ₲₳₲₳₲₳₲₳₲₳₲₳₳ ₳₳ ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ卂卄卂ﾌ卂ﾌﾌ卂 卂ᎶᎶ卂Ꮆ卂Ꮆ卂ᎶᎶ卂卂     ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂卄卂卄卂卄 卂卂卂卂卄卄 卂卄卂卂卂ㄩ卂ㄩㄩ卂卂ㄩ卂ㄩ卂ㄩ卂ㄩ    乃卂卂几几卂卂几卂卂 爪ㄖ几Ҝ乇ㄚ 山卂几ㄒ 乃卂几卂几卂卂卂几卂卂!!!
    -漫~*'¨¯¨'*·舞~ ᵐ𝔬Ň𝕂𝓔у 𝐠Ỗ 𝓒ℝÃ𝐳¥, 𝓂𝓞ⓝⓚⓔу 𝐆Ỗ в Δ Ň ａ 𝓔 𝕟 Δ 𝒆 ~. ⓤ𝐔𝓤ⓖ𝓰𝓖Δ𝔞ａÃ в𝓤ย𝔲𝔾Δａᗩ𝔸𝕒    ỮＵ𝓊Ǘ𝕒ㄩㄩ卂卂卂卂卂 ㄩ卂卂卂卂卂卂 卂卂卂卂卂卄卄卄 卂卄卄卂卄卂卄卂卄卄卄卄卂卄卄卂卄卄卂卄卄卂卄 卂ㄚㄚ卂ㄚ卂ㄚ卂ㄚㄚ卂ㄚ卂ㄚ卂ㄚ    ㄩᎶ卂Ꮆ卂Ꮆ卂Ꮆ卂Ꮆ卂Ꮆ卂卂 卂卂卂卂卂 ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ卂卄卂ﾌ卂ﾌﾌ卂 卂ᎶᎶ卂Ꮆ卂Ꮆ卂ᎶᎶ卂卂     ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂 卂卄卂卄ǟʝǟʝǟʝǟʝǟ ǟɦǟɦǟɦǟɦǟɦ ǟǟǟǟɦɦ ǟɦǟǟǟʊǟʊʊǟǟʊǟʊǟʊǟʊ    ɮǟǟռռǟǟռǟǟ ʍօռӄɛʏ աǟռȶ ɮǟռǟռǟǟǟռǟǟ!!!
    ₥Ø₦₭ɆɎ ₲Ø ₵Ɽ₳ⱫɎ, ₥Ø₦₭ɆɎ ₲Ø ฿ ₳ ₦ ₳ Ɇ ₦ ₳ Ɇ ~. ɄɄɄ₲₲₲₳₳₳₳ ฿ɄɄɄ₲₳₳₳₳₳    ɄɄɄɄ₳₳₳ Ʉ₳ɄɄ₳₳₳₳₳ Ʉ₳₳₳₳₳₳ ₳₳₳₳₳ⱧⱧⱧ ₳ⱧⱧ₳Ⱨ₳Ⱨ₳ⱧⱧⱧⱧ₳ⱧⱧ₳ⱧⱧ₳ⱧⱧ₳Ⱨ ₳ɎɎ₳Ɏ₳Ɏ₳ɎɎ₳Ɏ₳Ɏ₳Ɏ    Ʉ₲₳₲₳₲₳₲₳₲₳₲₳₳ ₳₳ ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ卂卄卂ﾌ卂ﾌﾌ卂 卂ᎶᎶ卂Ꮆ卂Ꮆ卂ᎶᎶ卂卂     ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂卄卂卄卂卄 卂卂卂卂卄卄 卂卄卂卂卂ㄩ卂ㄩㄩ卂卂ㄩ卂ㄩ卂ㄩ卂ㄩ    乃卂卂几几卂卂几卂卂 爪ㄖ几Ҝ乇ㄚ 山卂几ㄒ 乃卂几卂几卂卂卂几卂卂!!!
    -漫~*'¨¯¨'*·舞~ ᵐ𝔬Ň𝕂𝓔у 𝐠Ỗ 𝓒ℝÃ𝐳¥, 𝓂𝓞ⓝⓚⓔу 𝐆Ỗ в Δ Ň ａ 𝓔 𝕟 Δ 𝒆 ~. ⓤ𝐔𝓤ⓖ𝓰𝓖Δ𝔞ａÃ в𝓤ย𝔲𝔾Δａᗩ𝔸𝕒    ỮＵ𝓊Ǘ𝕒ａÃ ⓤᗩᑌ𝓤𝔞𝓪𝐚ᗩά 𝐔ᗩαⓐΔα𝒶 𝓐αΔ𝔸คⓗⓗ𝓱 𝐚ħ𝐇𝓐𝒽ᵃ𝔥ᗩн𝐡нĤάℍⒽαⒽ𝕙คℍ𝐇α𝒽 𝐀үуⓐ𝔶𝕒үάʸƳ𝓐𝐲Ａץⓐ𝕐    υg𝔞𝐠ค𝐠α𝕘ᗩＧ𝒶𝔤𝒶𝕒 α卂ᗩΔΔ 𝕌𝓎υａʸᵘⒶ𝐘Ⓐ𝕌у𝐚𝓾𝓎ⓐⒶ𝕒ᗩ ａᵍ𝔥Ａ𝐣𝓪卄𝓪נ𝐀јʲα 𝔞ᎶⒼ𝓪𝐠𝐀ᵍ𝓐𝓖𝔤Ã𝔞     ⓙⒶڶⓐ𝕁ค𝕁ⓐјα𝒿ⒶןＡ𝓳𝔞 𝓪ℍ𝒶н𝐀ħ𝔞ђ𝔸ђ Ãάα𝔞Ħⓗ ⓐ𝕙ᵃ𝐚𝓪𝔲ⓐＵỮ𝒶𝕒Ｕᗩᵘค𝓾Δ𝔲    乃ⒶÃＮ𝓃ᗩ𝐚𝐧ά𝓐 𝓶ᵒŇ𝐊ｅ𝓨 山ά几ｔ 𝕓𝓪ｎ卂ηα𝒶άᑎＡΔ!!! ~舞*'¨¯¨'*·~漫-
</p>

<style>
    *{
        text-align: justify;
        text-justify: distribute;
    }
    h1{
        font-size: 80px;
    }
</style>

// src/app/reglementation/banana_policy/page.jsx
export default function BananaPolicy() {
  return (
    <div>
      <h2>Banana Policy</h2>

      <p>
        Monkey go crazy, monkey go <i>B A N A E N A E ~</i>. UUUGGGAAAA BUUUGAAAAA
        UUUUAAA UAUUAAAAA UAAAAAA AAAAAHHH AHHAHAHAHHHHAHHAHHAHHAH AYYAYAYAYYAYAYAY
        UGAGAGAGAGAGAA AAAAA UYUAYUAYAUYAUYAAAA AGHAJAHAJAJJA AGGAGAGAGGAA
        JAJAJAJAJAJAJAJA AHAHAHAHAH <b>AAAAHH AHAAAUAUUAAUAUAUAU</b>
        <i>BAANNAANAA</i> MONKEY WANT <b>BANANAAANAA!!!</b>
      </p>
      <h2>MONEKY NEED BANANA NOWWWW !!!</h2>

      <p>
        BANAN 🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌
        🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌
        🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌
      </p>
      <p>
        𝓞ⓝⓚⓔу 𝐆Ỗ в Δ Ň ａ 𝓔 𝕟 Δ 𝒆 ~. ⓤ𝐔𝓤ⓖ𝓰𝓖Δ𝔞ａÃ в𝓤ย𝔲𝔾Δａᗩ𝔸𝕒
        ỮＵ𝓊Ǘ𝕒ａÃ ⓤᗩᑌ𝓤𝔞𝓪𝐚ᗩά 𝐔ᗩαⓐΔα𝒶 𝓐αΔ𝔸คⓗⓗ𝓱 𝐚ħ𝐇𝓐𝒽ᵃ𝔥ᗩн𝐡нĤάℍⒽαⒽ𝕙คℍ𝐇α𝒽 𝐀үуⓐ𝔶𝕒үάʸƳ𝓐𝐲Ａץⓐ𝕐
        υg𝔞𝐠ค𝐠α𝕘ᗩＧ𝒶𝔤𝒶𝕒 α卂ᗩΔΔ 𝕌𝓎υａ₳₳₳ ɄɎɄ₳ɎɄ₳Ɏ₳ɄɎ₳ɄɎ₳₳₳₳ ₳₲Ⱨ₳J₳Ⱨ₳J₳JJ₳ ₳₲₲₳₲₳₲₳₲₲₳₳
        J₳J₳J₳J₳J₳J₳J₳J₳ ₳Ⱨ₳Ⱨ₳Ⱨ₳Ⱨ₳Ⱨ ₳₳₳₳ⱧⱧ ₳Ⱨ₳₳₳Ʉ₳ɄɄ₳₳Ʉ₳Ʉ₳Ʉ₳Ʉ    ฿₳₳₦₦₳₳₦₳₳ ₥Ø₦₭ɆɎ
        ₩₳₦₮ ฿₳₦₳₦₳₳₳₦₳₳!!!
        爪ㄖ几Ҝ乇ㄚ Ꮆㄖ 匚尺卂乙ㄚ, 爪ㄖ几Ҝ乇ㄚ Ꮆㄖ 乃 卂 几 卂 乇 几 卂 乇 ~. ㄩㄩㄩᎶᎶᎶ卂卂卂卂 乃ㄩㄩㄩᎶ卂卂卂卂卂
        ㄩㄩㄩㄩ卂卂卂 ㄩ ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ卂卄卂ﾌ卂ﾌﾌ卂 卂ᎶᎶ卂Ꮆ卂Ꮆ卂ᎶᎶ卂卂     ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂
        卂卄卂卄ǟʝǟʝǟʝǟʝǟ ǟɦǟɦǟɦǟɦǟɦ ǟǟǟǟɦɦ ǟɦǟǟǟʊǟʊʊǟǟʊǟʊǟʊǟʊ    ɮǟǟռռǟǟռǟǟ ʍօռӄɛʏ աǟռȶ
        ɮǟռǟռǟǟǟռǟǟ!!!
        ₥Ø₦₭ɆɎ ₲Ø ₵Ɽ₳ⱫɎ, ₥Ø₦₭ɆɎ ₲Ø ฿ ₳ ₦ ₳ Ɇ ₦ ₳ Ɇ ~. ɄɄɄ₲₲₲₳₳₳₳ ฿ɄɄɄ₲₳₳₳₳₳
        ɄɄɄɄ₳₳₳ Ʉ₳ɄɄ₳₳₳₳₳ Ʉ₳₳₳₳₳₳ ₳₳₳₳₳ⱧⱧⱧ ₳ⱧⱧ₳Ⱨ₳Ⱨ₳ⱧⱧⱧⱧ₳ⱧⱧ₳ⱧⱧ₳ⱧⱧ₳Ⱨ ₳ɎɎ₳Ɏ₳Ɏ₳ɎɎ₳Ɏ₳Ɏ₳Ɏ
        Ʉ₲₳₲₳₲₳₲₳₲₳₲₳₳ ₳₳ ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ卂卄卂ﾌ卂ﾌﾌ卂 卂ᎶᎶ卂Ꮆ卂Ꮆ卂ᎶᎶ卂卂     ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂卄卂卄卂卄
        卂卂卂卂卄卄 卂卄卂卂卂ㄩ卂ㄩㄩ卂卂ㄩ卂ㄩ卂ㄩ卂ㄩ    乃卂卂几几卂卂₳ⱧⱧⱧⱧ₳ⱧⱧ₳ⱧⱧ₳ⱧⱧ₳Ⱨ ₳ɎɎ₳Ɏ₳Ɏ₳ɎɎ₳Ɏ₳Ɏ₳Ɏ
        Ʉ₲₳₲₳₲₳₲₳₲₳₲₳₳ ₳₳ ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ卂卄卂ﾌ卂ﾌﾌ卂 卂ᎶᎶ卂Ꮆ卂Ꮆ卂ᎶᎶ卂卂     ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂卄卂卄卂卄
        卂卂卂卂卄卄 卂卄卂卂卂ㄩ卂ㄩㄩ卂卂ㄩ卂ㄩ卂ㄩ卂ㄩ    乃卂卂几几卂卂几卂卂 爪ㄖ几Ҝ乇ㄚ 山卂几ㄒ 乃卂几卂几卂Δ 𝕌𝓎υａʸᵘⒶ𝐘Ⓐ𝕌у𝐚𝓾𝓎ⓐⒶ𝕒ᗩ
        ａᵍ𝔥Ａ𝐣𝓪卄𝓪נ𝐀јʲα 𝔞ᎶⒼ𝓪𝐠𝐀ᵍ𝓐𝓖𝔤Ã𝔞     ⓙⒶڶⓐ𝕁ค𝕁ⓐјα𝒿ⒶןＡ𝓳𝔞 𝓪ℍ𝒶н𝐀ħ𝔞ђ𝔸ђ Ãάα𝔞Ħⓗ
        ⓐ𝕙ᵃ𝐚𝓪𝔲ⓐＵỮ𝒶𝕒Ｕᗩᵘค𝓾Δ𝔲    乃ⒶÃＮ𝓃ᗩ𝐚𝐧ά𝓐 𝓶ᵒŇ𝐊ｅ𝓨 山ά几ｔ 𝕓𝓪ｎ卂ηα𝒶άᑎＡΔ!!! ~舞*'¨¯¨'*·~漫-ǟɦɦ
        ǟɦǟǟǟʊǟʊʊǟǟʊǟʊǟʊǟʊ    ɮǟǟռռǟǟռǟǟ ʍօռӄɛʏ աǟռȶ ɮǟռǟռǟǟǟռǟǟ!!!
        ₥Ø₦₭ɆɎ ₲Ø ₵Ɽ₳ⱫɎ, ₥Ø₦₭ɆɎ ₲Ø ฿ ₳ ₦ ₳ Ɇ ₦ ₳ Ɇ ~. ɄɄɄ₲₲₲₳₳₳₳ ฿ɄɄɄ₲₳₳₳₳₳
        ɄɄɄɄ₳₳₳ Ʉ₳ɄɄ₳₳₳₳₳ Ʉ₳₳₳₳₳₳ ₳₳₳₳₳ⱧⱧⱧ ₳ⱧⱧ₳Ⱨ₳Ⱨ₳ⱧⱧⱧⱧ₳ⱧⱧ₳ⱧⱧ₳ⱧⱧ₳Ⱨ ₳ɎɎ₳Ɏ₳Ɏ₳ɎɎ₳Ɏ₳Ɏ₳Ɏ
        Ʉ₲₳₲₳₲₳₲₳₲₳₲₳₳ ₳₳ ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ卂卄卂ﾌ卂ﾌﾌ卂 卂ᎶᎶ卂Ꮆ卂Ꮆ卂ᎶᎶ卂卂     ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂卄卂卄卂卄
        卂卂卂卂卄卄 卂卄卂卂卂ㄩ卂ㄩㄩ卂卂ㄩ卂ㄩ卂ㄩ卂ㄩ    乃卂卂几几卂卂₳ⱧⱧⱧⱧ₳ⱧⱧ₳ⱧⱧ₳ⱧⱧ₳Ⱨ ₳ɎɎ₳Ɏ₳Ɏ₳ɎɎ₳Ɏ₳Ɏ₳Ɏ
        Ʉ₲₳₲₳₲₳₲₳₲₳₲₳₳ ₳₳ ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ𝓪𝐚ᗩά 𝐔ᗩαⓐΔα𝒶 𝓐αΔ𝔸คⓗⓗ𝓱 𝐚ħ𝐇𝓐𝒽ᵃ𝔥ᗩн𝐡нĤάℍⒽαⒽ𝕙คℍ𝐇α𝒽
        𝐀үуⓐ𝔶𝕒үάʸƳ𝓐𝐲Ａץⓐ𝕐    υg𝔞𝐠ค𝐠α𝕘ᗩＧ𝒶𝔤𝒶𝕒 α卂ᗩΔΔ 𝕌
      </p>
      <h1>B A N A N</h1>
      <p>
        ✧✴ 🎀 𝐵𝒜𝒩𝒜𝒩𝒜 🎀 ✴✧
        <br />
        <br />
        <br />
        ʍօռӄɛʏ ɢօ ƈʀǟʐʏ, ʍօռӄɛʏ ɢօ ɮ ǟ ռ ǟ ɛ ռ ǟ ɛ ~. ʊʊʊɢɢɢǟǟǟǟ ɮʊʊʊɢǟǟǟǟǟ
        ʊʊʊʊǟǟǟ ʊǟʊʊǟǟǟǟǟ ʊǟǟǟǟǟǟ ǟǟǟǟǟɦɦɦ ǟɦɦǟɦǟɦǟɦɦɦɦǟɦɦǟɦɦǟɦɦǟɦ ǟʏʏǟʏǟʏǟʏʏǟʏǟʏǟʏ
        ʊɢǟɢǟɢǟɢǟɢǟɢǟǟ ǟǟǟǟǟ ʊʏʊǟʏʊǟʏǟʊʏǟʊʏǟǟǟǟ ǟɢɦǟʝǟɦǟʝǟʝʝǟ ǟɢɢǟɢǟɢǟɢɢǟǟ
        ʝǟʝǟʝǟʝǟʝǟʝǟʝǟʝǟ ǟɦǟɦǟɦǟɦǟɦ ǟǟǟǟɦɦ ǟɦǟǟǟʊǟʊʊǟǟʊǟʊǟʊǟʊ    ɮǟǟռռǟǟռǟǟ ʍօռӄɛʏ աǟռȶ
        ɮǟռǟռǟǟǟռǟǟ!!!
        ₥Ø₦₭ɆɎ ₲Ø ₵Ɽ₳ⱫɎ, ₥Ø₦₭ɆɎ ₲Ø ฿ ₳ ₦ ₳ Ɇ ₦ ₳ Ɇ ~. ɄɄɄ₲₲₲₳₳₳₳ ฿ɄɄɄ₲₳₳₳₳₳
        ɄɄɄɄ₳₳₳ Ʉ₳ɄɄ₳₳₳₳₳ Ʉ₳₳₳₳₳₳ ₳₳₳₳₳ⱧⱧⱧ ₳ⱧⱧ₳Ⱨ₳Ⱨ₳ⱧⱧⱧⱧ₳ⱧⱧ₳ⱧⱧ₳ⱧⱧ₳Ⱨ ₳ɎɎ₳Ɏ₳Ɏ₳ɎɎ₳Ɏ₳Ɏ₳Ɏ
        Ʉ₲₳₲₳₲₳₲₳₲₳₲₳₳ ₳₳ ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ卂卄卂ﾌ卂ﾌﾌ卂 卂ᎶᎶ卂Ꮆ卂Ꮆ卂ᎶᎶ卂卂     ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂
        卂卄卂卄卂卄卂卄卂卄 卂卂卂卂卄卄 卂卄卂卂卂ㄩ卂ㄩㄩ卂卂ㄩ卂ㄩ卂ㄩ卂ㄩ    乃卂卂几几卂卂几卂卂 爪ㄖ几Ҝ乇ㄚ 山卂几ㄒ
        乃卂几卂几卂卂卂几卂卂!!!
        -漫~*'¨¯¨'*·舞~ ᵐ𝔬Ň𝕂𝓔у 𝐠Ỗ 𝓒ℝÃ𝐳¥, 𝓂𝓞ⓝⓚⓔу 𝐆Ỗ в Δ Ň ａ 𝓔 𝕟 Δ 𝒆 ~. ⓤ𝐔𝓤ⓖ𝓰𝓖Δ𝔞ａÃ
        в𝓤ย𝔲𝔾Δａᗩ𝔸𝕒    ỮＵ𝓊Ǘ𝕒ａÃ ⓤᗩᑌ𝓤𝔞𝓪𝐚ᗩά 𝐔ᗩαⓐΔα𝒶 𝓐αΔ𝔸คⓗⓗ𝓱 𝐚ħ𝐇𝓐𝒽ᵃ𝔥ᗩн𝐡нĤάℍⒽαⒽ𝕙คℍ𝐇α𝒽 𝐀үуⓐ𝔶𝕒үάʸƳ𝓐𝐲Ａץⓐ𝕐
        υg𝔞𝐠ค𝐠α𝕘ᗩＧ𝒶𝔤𝒶𝕒 α卂ᗩΔΔ 𝕌𝓎υａ₳₳₳ ɄɎɄ₳ɎɄ₳Ɏ₳ɄɎ₳ɄɎ₳₳₳₳ ₳₲Ⱨ₳J₳Ⱨ₳J₳JJ₳ ₳₲₲₳₲₳₲₳₲₲₳₳
        J₳J₳J₳J₳J₳J₳J₳J₳ ₳Ⱨ₳Ⱨ₳Ⱨ₳Ⱨ₳Ⱨ ₳₳₳₳ⱧⱧ ₳Ⱨ₳₳₳Ʉ₳ɄɄ₳₳Ʉ₳Ʉ₳Ʉ₳Ʉ    ฿₳₳₦₦₳₳₦₳₳ ₥Ø₦₭ɆɎ
        ₩₳₦₮ ฿₳₦₳₦₳₳₳₦₳₳!!!
        爪ㄖ几Ҝ乇ㄚ Ꮆㄖ 匚尺卂乙ㄚ, 爪ㄖ几Ҝ乇ㄚ Ꮆㄖ 乃 卂 几 卂 乇 几 卂 乇 ~. ㄩㄩㄩᎶᎶᎶ卂卂卂卂 乃ㄩㄩㄩᎶ卂卂卂卂卂
        ㄩㄩㄩㄩ卂卂卂 ㄩ ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ卂卄卂ﾌ卂ﾌﾌ卂 卂ᎶᎶ卂Ꮆ卂Ꮆ卂ᎶᎶ卂卂     ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂
        卂卄卂卄ǟʝǟʝǟʝǟʝǟ ǟɦǟɦǟɦǟɦǟɦ ǟǟǟǟɦɦ ǟɦǟǟǟʊǟʊʊǟǟʊǟʊǟʊǟʊ    ɮǟǟռռǟǟռǟǟ ʍօռӄɛʏ աǟռȶ
        ɮǟռǟռǟǟǟռǟǟ!!!
        ₥Ø₦₭ɆɎ ₲Ø ₵Ɽ₳ⱫɎ, ₥Ø₦₭ɆɎ ₲Ø ฿ ₳ ₦ ₳ Ɇ ₦ ₳ Ɇ ~. ɄɄɄ₲₲₲₳₳₳₳ ฿ɄɄɄ₲₳₳₳₳₳
        ɄɄɄɄ₳₳₳ Ʉ₳ɄɄ₳₳₳₳₳ Ʉ₳₳₳₳₳₳ ₳₳₳₳₳ⱧⱧⱧ ₳ⱧⱧ₳Ⱨ₳Ⱨ₳ⱧⱧⱧⱧ₳ⱧⱧ₳ⱧⱧ₳ⱧⱧ₳Ⱨ ₳ɎɎ₳Ɏ₳Ɏ₳ɎɎ₳Ɏ₳Ɏ₳Ɏ
        Ʉ₲₳₲₳₲₳₲₳₲₳₲₳₳ ₳₳ ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ卂卄卂ﾌ卂ﾌﾌ卂 卂ᎶᎶ卂Ꮆ卂Ꮆ卂ᎶᎶ卂卂     ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂卄卂卄卂卄
        卂卂卂卂卄卄 卂卄卂卂卂ㄩ卂ㄩㄩ卂卂ㄩ卂ㄩ卂ㄩ卂ㄩ    乃卂卂几几卂卂几卂卂 爪ㄖ几Ҝ乇ㄚ 山卂几ㄒ 乃卂几卂几卂卂卂几卂卂!!!
        -漫~*'¨¯¨'*·舞~ ᵐ𝔬Ň𝕂𝓔у 𝐠Ỗ 𝓒ℝÃ𝐳¥, 𝓂𝓞ⓝⓚⓔу 𝐆Ỗ в Δ Ň ａ 𝓔 𝕟 Δ 𝒆 ~. ⓤ𝐔𝓤ⓖ𝓰𝓖Δ𝔞ａÃ
        в𝓤ย𝔲𝔾Δａᗩ𝔸𝕒    ỮＵ𝓊Ǘ𝕒ㄩㄩ卂卂卂卂卂 ㄩ卂卂卂卂卂卂 卂卂卂卂卂卄卄卄 卂卄卄卂卄卂卄卂卄卄卄卄卂卄卄卂卄卄卂卄卄卂卄
        卂ㄚㄚ卂ㄚ卂ㄚ卂ㄚㄚ卂ㄚ卂ㄚ卂ㄚ    ㄩᎶ卂Ꮆ卂Ꮆ卂Ꮆ卂Ꮆ卂Ꮆ卂卂 ₳₳₳₳₳ ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ卂卄卂ﾌ卂ﾌﾌ卂
        卂ᎶᎶ卂Ꮆ卂Ꮆ卂ᎶᎶ卂卂     ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂 ǟɦǟɦǟɦǟɦǟɦ ǟǟǟǟɦɦ ǟɦǟǟǟʊǟʊʊǟǟʊǟʊǟʊǟʊ
        ɮǟǟռռǟǟռǟǟ ʍօռӄɛʏ աǟռȶ ɮǟռǟռǟǟǟռǟǟ!!!
        ₥Ø₦₭ɆɎ ₲Ø ₵Ɽ₳ⱫɎ, ₥Ø₦₭ɆɎ ₲Ø ฿ ₳ ₦ ₳ Ɇ ₦ ₳ Ɇ ~. ɄɄɄ₲₲₲₳₳₳₳ ฿ɄɄɄ₲₳₳₳₳₳
        ɄɄɄɄ₳₳₳ Ʉ₳ɄɄ₳₳₳₳₳ Ʉ₳₳₳₳₳₳ ₳₳₳₳₳ⱧⱧⱧ ₳ⱧⱧ₳Ⱨ₳Ⱨ₳ⱧⱧⱧⱧ₳ⱧⱧ₳ⱧⱧ₳ⱧⱧ₳Ⱨ ₳ɎɎ₳Ɏ₳Ɏ₳ɎɎ₳Ɏ₳Ɏ₳Ɏ
        Ʉ₲₳₲₳₲₳₲₳₲₳₲₳₳ ₳₳ ㄩㄚㄩ卂ㄚㄩ卂ㄚ卂ㄩㄚ卂ㄩㄚ卂卂卂卂 卂Ꮆ卄卂ﾌ卂卄卂ﾌ卂ﾌﾌ卂 卂ᎶᎶ卂Ꮆ卂Ꮆ卂ᎶᎶ卂卂     ﾌ卂ﾌ卂ﾌ卂ﾌ卂ﾌ卂卄卂卄卂卄
        卂卂卂卂卄卄 卂卄卂卂卂ㄩ卂ㄩㄩ卂卂ㄩ卂ㄩ卂ㄩ卂ㄩ    乃卂卂几几卂卂几卂卂 爪ㄖ几Ҝ乇ㄚ 山卂几ㄒ 乃卂几卂几卂卂卂几卂卂!!!
        -漫~*'¨¯¨'*·舞~ ᵐ𝔬Ň𝕂𝓔у 𝐠Ỗ 𝓒ℝÃ𝐳¥, 𝓂𝓞ⓝⓚⓔу 𝐆Ỗ в Δ Ň ａ 𝓔 𝕟 Δ 𝒆 ~. ⓤ𝐔𝓤ⓖ𝓰𝓖Δ𝔞ａÃ
        в𝓤ย𝔲𝔾Δａᗩ𝔸𝕒    ỮＵ𝓊Ǘ𝕒ａÃ ⓤᗩᑌ𝓤𝔞𝓪𝐚ᗩά 𝐔ᗩαⓐΔα𝒶 𝓐αΔ𝔸คⓗⓗ𝓱 𝐚ħ𝐇𝓐𝒽ᵃ𝔥ᗩн𝐡нĤάℍⒽαⒽ𝕙คℍ𝐇α𝒽 𝐀үуⓐ𝔶𝕒үάʸƳ𝓐𝐲Ａץⓐ𝕐
        υg𝔞𝐠ค𝐠α𝕘ᗩＧ𝒶𝔤𝒶𝕒 α卂ᗩΔΔ 𝕌𝓎υａʸᵘⒶ𝐘Ⓐ𝕌у𝐚𝓾𝓎ⓐⒶ𝕒ᗩ ａᵍ𝔥Ａ𝐣𝓪卄𝓪נ𝐀јʲα 𝔞ᎶⒼ𝓪𝐠𝐀ᵍ𝓐𝓖𝔤Ã𝔞
        ⓙⒶڶⓐ𝕁ค𝕁ⓐјα𝒿ⒶןＡ𝓳𝔞 𝓪ℍ𝒶н𝐀ħ𝔞ђ𝔸ђ Ãάα𝔞Ħⓗ ⓐ𝕙ᵃ𝐚𝓪𝔲ⓐＵỮ𝒶𝕒Ｕᗩᵘค𝓾Δ𝔲    乃ⒶÃＮ𝓃ᗩ𝐚𝐧ά𝓐 𝓶ᵒŇ𝐊ｅ𝓨
        山ά几ｔ 𝕓𝓪ｎ卂ηα𝒶άᑎＡΔ!!! ~舞*'¨¯¨'*·~漫-
      </p>
    </div>
  );
}
