// src/lib/components/Rolldown.svelte
<script lang="ts">
    import { afterUpdate } from "svelte";

    export let default_open: boolean = false;
    export let closed_height: string = "15vh";

    let open: boolean = default_open;
    let plus_needed: boolean = false;

    let main: HTMLElement;

    afterUpdate(()=>{
        if (!main) return;
        plus_needed = plus_needed || open || main.scrollHeight != main.clientHeight;
    });

    const roll = ()=>{
        open=!open;
        setTimeout(()=>{
            main.scrollIntoView({
                behavior: 'smooth',
                block: 'center',
                inline: 'start',
            });
        }, 200);
    };
</script>

<div bind:this={main} class="main" style={open ? "" : `max-height: ${closed_height};overflow: hidden !important;`}>
    <slot>
        No content provided...
    </slot>
</div>
{#if plus_needed}
    <div class="plus">
        <button on:click={roll}>{open ? "- cacher -" : "+ afficher plus +"}</button>
    </div>
{/if}

<style>
    div.main{
        overflow: scroll;
        max-height: 90vh;
        transition: max-height 0.2s ease-in-out;
    }
    .plus{
        margin-top: 0.2rem;
        text-align: center;
    }
</style>

// src/components/Rolldown.jsx
'use client';

import { useState, useRef, useEffect } from 'react';

export default function Rolldown({ children, defaultOpen = false, closedHeight = '15vh' }) {
  const [open, setOpen] = useState(defaultOpen);
  const [plusNeeded, setPlusNeeded] = useState(false);
  const mainRef = useRef(null);

  useEffect(() => {
    if (mainRef.current) {
      setPlusNeeded(open || mainRef.current.scrollHeight !== mainRef.current.clientHeight);
    }
  }, [open, children]);

  const roll = () => {
    setOpen(!open);
    setTimeout(() => {
      mainRef.current?.scrollIntoView({
        behavior: 'smooth',
        block: 'center',
        inline: 'start',
      });
    }, 200);
  };

  return (
    <div>
      <div
        ref={mainRef}
        className="main"
        style={open ? {} : { maxHeight: closedHeight, overflow: 'hidden' }}
      >
        {children}
      </div>
      {plusNeeded && (
        <div className="plus">
          <button onClick={roll}>{open ? '- cacher -' : '+ afficher plus +'}</button>
        </div>
      )}
    </div>
  );
}
