// src/routes/restricted/anciens/[slug]/+page.svelte
<script lang='ts'>
    import { enhance } from '$app/forms';
    import Markdown from '$lib/components/Markdown.svelte';
    import { user_data_into_forms } from '$lib/transformers';

    // /** @type {import('./$types').PageData} */
    // export let data;
    // export let form;
    
    let { data, form } = $props();


    // $: sectioned = user_data_into_forms(data.subject)
    //     .map(({n, l})=>({n, l: l
    //         .filter(({k})=>k!="description" && data.subject && data.subject.hasOwnProperty(k))}));

    let sectioned = $state<{
        id: string;
        email: string | null;
        login: string;
        admin: boolean;
        prenom: string;
        nom: string | null;
        contact: string[];
        grad_year: number;
        nationalite: string[];
        moyenneL2: number | null;
        moyenneL3: number | null;
        admis: string[];
        choisi: string;
        travails: string[];
        description: string;
        createdAt: Date;
        updatedAt: Date;
    }>();

    $effect(()=>{
        data.subject.then(subject=>{
            if(!data) return;
            sectioned = user_data_into_forms(subject)
                .map(({n, l})=>({n, l: l
                    .filter(({k})=>k!="description" && subject && subject.hasOwnProperty(k))}));

        })
    });

    /** @type {string | undefined}*/
    let user_input = $state("user login");
</script>


{#await data.subject}
    <p>Loading...</p>
{:then subject} 

    <h1>{subject?.prenom} {subject?.nom || "😎🤐"}</h1>

    {#each sectioned as {n, l: list}}
    <fieldset>
        <legend>{n}</legend>
        <table>
            <tbody>
                {#each list as {k, l, v}}
                <tr>
                    <th>{l}</th>
                    <td>{v}</td>
                </tr>
                {/each}
            </tbody>
        </table>
    </fieldset>
    {/each}

    {#if data.user?.admin}
    <h2>Admin</h2>
        <fieldset>
            {#if form?.error}<p class="error">Erreur serveur: "{form.error}"</p>{/if}
            {#if form?.success}<p class="success">Update successfull!!!! </p>{/if}        
            <legend>Admin actions</legend>
            <fieldset>
                <legend>admin privilages</legend>
                <form method="POST" action="?/user_status_change" use:enhance>
                    <input name="user_id" type="text" value={subject?.id} hidden/>
                    <button name="admin_rights_on" disabled={subject?.admin}>Give admin permissions</button>
                    <button name="admin_rights_off" disabled={!subject?.admin || subject.id == data.user.id}>Remove admin permissions</button>
                </form>
            </fieldset>
            <fieldset>
                <legend>delete user</legend>
                <form method="POST" action="?/user_delete" use:enhance>
                    <input name="user_id" type="text" value={subject?.id} hidden/>
                    <input bind:value={user_input} type="text">
                    <button name="delete_user" disabled={user_input!=subject?.login || subject?.admin || subject?.id == data.user.id}>Delete this user</button>
                </form>
            </fieldset>
        </fieldset>
    {/if}

    <h2>Conseils / description : </h2>
    <Markdown markdown={subject?.description || ""}/>
{/await}


<style>
    td{
        padding-left: 7px;
        border-bottom: dotted 1px gray;
    }
    tr > th{
        text-align: right;
        padding-right: 7px;
        border-right: solid 1px gray;
        width: 100px;
    }
    fieldset{
        margin-top: 20px;
    }
    .error{
        color: red;
    }
    .success{
        color: green;
    }
</style>

// src/app/restricted/anciens/[slug]/page.jsx
import prisma from '../../../../../lib/prisma';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '../../../../api/auth/[...nextauth]/route';
import { notFound } from 'next/navigation';
import Markdown from '../../../../../components/Markdown';
import { user_data_into_forms } from '../../../../../lib/transformers';
import AdminActions from './admin-actions';

export default async function AncienPage({ params }) {
  const session = await getServerSession(authOptions);

  if (!session) {
    return {
      redirect: {
        destination: `/login?redirect=/restricted/anciens/${params.slug}`,
        permanent: false,
      },
    };
  }

  const subject = await prisma.user.findFirst({
    where: {
      id: params.slug,
    },
    select: {
      // never show
      password: false,
      // show if admin
      admin: session.user.admin,
      updatedAt: session.user.admin,
      login: session.user.admin,
      id: session.user.admin,
      // safe info
      prenom: true,
      nom: true,
      email: true,
      contact: true,
      grad_year: true,
      nationalite: true,
      moyenneL2: true,
      moyenneL3: true,
      admis: true,
      choisi: true,
      travails: true,
      description: true,
      createdAt: true,
    },
  });

  if (!subject) {
    notFound();
  }

  const sectioned = user_data_into_forms(subject).map(({ n, l }) => ({
    n,
    l: l.filter(({ k }) => k !== 'description' && subject && subject.hasOwnProperty(k)),
  }));

  return (
    <div>
      <h1>
        {subject?.prenom} {subject?.nom || '😎🤐'}
      </h1>

      {sectioned.map(({ n, l: list }) => (
        <fieldset key={n}>
          <legend>{n}</legend>
          <table>
            <tbody>
              {list.map(({ k, l, v }) => (
                <tr key={k}>
                  <th>{l}</th>
                  <td>{v}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </fieldset>
      ))}

      {session.user.admin && <AdminActions subject={subject} user={session.user} />}

      <h2>Conseils / description : </h2>
      <Markdown markdown={subject?.description || ''} />
    </div>
  );
}
