// src/components/Nav.jsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useSession } from 'next-auth/react';

export default function Nav() {
  const pathname = usePathname();
  const { data: session } = useSession();

  const pages = [
    ['/', 'accueil'],
    ['/restricted/anciens', 'anciens'],
    ['/conseils', 'conseils'],
    ['/restricted/external/Google Drive', 'drive'],
    // ["/restricted/faq", "FAQ"],
  ];

  return (
    <div id="nav-cont">
      <nav>
        <div className="logo">
          <span>Æ PIMA</span>
        </div>
        {pages.map((p) => (
          <div key={p[0]}>
            <Link href={p[0]} className={pathname == p[0] ? 'current' : ''}>
              {' '}
              {p[1]}{' '}
            </Link>
          </div>
        ))}
        <div className="login">
          {session ? (
            <Link href="/restricted/user"> {session.user.prenom}</Link>
          ) : (
            <Link href="/login"> connexion </Link>
          )}
        </div>
      </nav>
    </div>
  );
}

// src/lib/components/Nav.svelte
<script lang="ts">
    import { getContext } from "svelte";
    import { page } from '$app/stores';
    import type { Writable } from "svelte/store";

    const pages: string[][] = [
        ["/", "accueil"],
        ["/restricted/anciens", "anciens"],
        ["/conseils", "conseils"],
        ["/restricted/external/Google Drive", "drive"],
        // ["/restricted/faq", "FAQ"],
    ];

    const user = getContext<Writable<App.Locals['user']>>('user');
</script>


<div id="nav-cont">
    <nav>
        <div class="logo">
            <span>Æ PIMA</span>
        </div>
        {#each pages as p}
            <div>
                <a data-sveltekit-preload-data="off" data-sveltekit-preload-code="off" href={p[0]} class={$page.url.pathname == p[0] ? "current":""}> {p[1]} </a> 
            </div>
        {/each}
        <div class="login">
            {#if $user}
                <a data-sveltekit-preload-data="off" data-sveltekit-preload-code="off" href="/restricted/user"> {$user.prenom}</a>  
            {:else}
                <a data-sveltekit-preload-data="off" data-sveltekit-preload-code="off" href="/login"> connexion </a>
            {/if}
        </div>
    </nav>
</div>

<style>
    #nav-cont{
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;
        right: 0;
        background: var(--background-color);
    }
    @media (hover:hover) {
        #nav-cont{
            background: none;
        }
        nav{
            backdrop-filter: blur(5px);
        }
    }
    nav{
        display: flex;
        justify-content :right;
        align-items: center;
        padding: 1rem;
        flex-direction: row;
        flex-wrap: wrap;
        gap: 0.5rem;
    }
    nav div *{
        font-weight: normal;
        text-decoration: none;
        font-size: larger;
        padding: 4px;
        margin: 5px;
    }
    a.current{
        color: var(--background-color);
        background-color: var(--font-color);
    }
    .logo{
        flex-grow: 1;
    }
    .login{
        border-left: 1px solid var(--font-color);
        padding-left: 0.5rem;
    }
</style>
